Реализовать модели данных, REST-контроллеры, валидацию и логирование.
NikAndDeg/java-filmorate pull request #5
Opened 2024-01-17 14:01 UTC by NikAndDeg

2024-01-18 13:08 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		log.info("Post [" + film.toString() + "].");
в логгере удобно использовать плейсхолдер {} что бы вставить какие-то значения в лог, 
там и выглядит лучше, и работает чуть оптимальней 

аналогично в других местах

2024-01-18 13:10 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		film.setId(++idCounter);
Расчёт айдишника можно вынести в отдельный метод, что бы было удобней управлять логикой создания айдишника в одном месте

2024-01-18 13:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +	private void safeUserInfo(User user) {
семантически чуть грамотней было бы save или store так как safe - это не глагол

2024-01-18 13:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/validator/BirthDateValidation.java
> +public @interface BirthDateValidation {
отличная идея сделать валидацию через аннотацию, так код выглядит чище

2024-01-18 13:16 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/validator/ReleaseDateValidator.java
> +}
по заданию, необходимы тесты, которые будут проверять валидацию

2024-01-19 17:24 UTC, NikAndDeg commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		log.info("Post [" + film.toString() + "].");
Сбацал

2024-01-19 17:24 UTC, NikAndDeg commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		film.setId(++idCounter);
Сбацал

2024-01-19 17:25 UTC, NikAndDeg commented on src/main/java/ru/yandex/practicum/filmorate/validator/ReleaseDateValidator.java
> +}
Сбацал как смог.

2024-01-20 19:19 UTC, Fleaman777 requested changes

2024-01-20 19:19 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/validator/ValidatorTest.java
> +
тесты на film валидацю должны быть на эти кейсы 

название не может быть пустым;
максимальная длина описания — 200 символов;
дата релиза — не раньше 28 декабря 1895 года;
продолжительность фильма должна быть положительной.


для юзера все хорошо

2024-01-20 19:19 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/validator/ValidatorTest.java
> +}
лучше разделить этот тестовый класс на 2 разных, для юзеров и фильмов, 
так их проще будет поддерживать и в них ориентироваться

2024-01-22 14:10 UTC, NikAndDeg commented on src/test/java/ru/yandex/practicum/filmorate/validator/ValidatorTest.java
> +
Сбацал

2024-01-22 14:10 UTC, NikAndDeg commented on src/test/java/ru/yandex/practicum/filmorate/validator/ValidatorTest.java
> +}
Сбацал

2024-01-25 08:37 UTC, merged