Изменить архитектуру. Добавить Storage и Service. Реализовать добавле…
NikAndDeg/java-filmorate pull request #6
Opened 2024-01-29 19:35 UTC by NikAndDeg

…ние лайков, добавление в друзья.

2024-01-30 19:02 UTC, Fleaman777 requested changes

2024-02-01 17:51 UTC, NikAndDeg commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +	UserStorage userStorage;
Сбацал

2024-02-01 17:51 UTC, NikAndDeg commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +		);
Сбацал

2024-02-01 17:53 UTC, NikAndDeg commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +			throw new LikeAlreadyAddedException("User already liked film.");
Сбацал.

2024-02-02 15:44 UTC, Fleaman777 approved these changes

2024-02-03 10:36 UTC, merged