Add database
NikAndDeg/java-filmorate pull request #7
Opened 2024-02-25 11:36 UTC by NikAndDeg

2024-02-26 19:46 UTC, Fleaman777 requested changes

2024-02-26 19:46 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDaoImpl.java
> +	private final MPARatingDao ratingDao;
dao/repository/storage классы не должны быть зависимы на другие сторедж классы, они должны отвечать только за взаимодействием с какой-то одной сущностью(фильмы, юзеры...), по сути иметь зависимость только на JdbcTemplate jdbcTemplate, тем самым будет соблюдаться принцип разделения ответсвенности,
такой класс будет легче поддерживать, тестрировать, расширять
если будут нужны какие-то спицифические данные из других дао классов из можно будет получить через слой сервис,
методы репозиториев не должны выполнять специфическую логику приложения, в основном это достать, положить в одну таблицу, либо достать из нескольких при помощи джоинов,
если нужно положить/взять что-то, что находится в др таблицах, то это все собирается/делается на уровне соответствующего метода в сервисе

2024-02-26 19:46 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmGenresDaoImpl.java
> +		);
молодец, правильное обновление, когда необходимо это сделать для нескольких записей одновременно, а не просто в цикле обычным запросом

2024-02-26 19:46 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/user/UserDaoImpl.java
> +		String sql = "UPDATE users SET email = ?, login = ?, user_name = ?, birthday = ? WHERE user_id = ?;";
хороший щапрос с точки зрения читаемости, 
когда названия таблиц, столбцов выделены одним регистром(нижнем), а названия ключевых слов SELECT, UPDATE и пр в верхнем регистре

2024-02-26 19:46 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/user/UserFriendsDaoImpl.java
> +	public List<Integer> getMutualFriend(int userId, int otherUserId) {
с подобными методами двоякая ситуация, с одной стороны, удобно и быстро все выполнить в одном запросе, 
но с другой, главное не переборщить с самим запросом, тк в конечном итоге он может быть тяжелочитаем + не очень оптимальным + сложнотестируемым и тп, в таком случае логику лучше разделить и соответиственно выполнять на уровне сервиса, а сами заросы а бд будут более простыми

конкретно в этом случае, у теюя хороший метод, но главное не увелекаться вложенными запросами)

2024-02-26 19:46 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmLikesDaoImplTest.java
> +		likesDao.add(3, 1);
хорошо было общую для всех тестов часть вынести в метод с аннотацией @BeforeEach

2024-02-26 19:46 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmLikesDaoImplTest.java
> +@SpringBootTest
спрингБут тест хорошо, но по заданию нужно еще использвать @@JdbcTest

2024-02-26 19:46 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/user/UserFriendsDaoImplTest.java
> +}
ну, про другие тесты ты и сам все знаешь)

2024-02-27 11:50 UTC, NikAndDeg commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDaoImpl.java
> +	private final MPARatingDao ratingDao;
Спасибо за развернутый ответ! Этот момент меня как раз смущал, но я от чего-то подумал, что dao-классы могут обращаться друг к другу.

2024-02-29 06:52 UTC, NikAndDeg commented
Дорогому мистеру ревьюеру № 2.
Оказывается, мне "критически важно закрыть" проект побыстрее. Можно ли просить засчитать мне проект, если не будут найдены еще критические моменты?
Все найдены некритические моменты обязуюсь исправить)
![2024-02-29_11-46-00](https://github.com/NikAndDeg/java-filmorate/assets/137883498/30d7bd4a-17b7-4eb5-972a-a88f2c001b61)

2024-02-29 13:08 UTC, Fleaman777 approved these changes

2024-03-02 19:21 UTC, merged